stages:
  - test
  - deploy
  
image: "mcr.microsoft.com/dotnet/sdk:9.0"

before_script:
  - export PATH="$PATH:/root/.dotnet/tools"
  - apt-get update
  - apt-get install -y bc
  - dotnet tool install -g nbgv

test:
  stage: test
  script:
    - dotnet build
    - dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura
    - chmod +x ./print-dotnet-coverage.sh
    - ./print-dotnet-coverage.sh TSPCoordinator.Tests/
  coverage: /TOTAL_COVERAGE=(\d+.\d+)/
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: TSPCoordinator.Tests/coverage.cobertura.xml
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  only:
    - master
    - tags
    - merge_requests
    
deploy:
  stage: deploy
  script:
    - cd TSPCoordinator
    
  when: manual
  only:
    - master
    - tags
