stages:
  - test
  - deploy
  
image: "mcr.microsoft.com/dotnet/sdk:7.0"

before_script:
  - apt-get update
  - apt-get install -y bc
  - dotnet tool install -g nbgv

test:
  stage: test
  script:
    - dotnet test --collect:"XPlat Code Coverage"
    - chmod +x ./print-dotnet-coverage.sh
    - ./print-dotnet-coverage.sh TSPCoordinator.Tests/TestResults/
  coverage: /TOTAL_COVERAGE=(\d+.\d+)/
  artifacts:
    when: always
    reports:
      cobertura: TSPCoordinator.Tests/TestResults/*/coverage.cobertura.xml
  only:
    - master
    - tags
    - merge_requests
    
deploy:
  stage: deploy
  script:
    - cd TSPCoordinator
    
  when: manual
  only:
    - master
    - tags
